---
- name: install collectd 
  yum: 
    name: collectd
    state: present
  
- name: push collectd config to host
  template:
    src: collectd.conf
    dest: /etc/collectd.conf
  notify:
    - restart collectd

- name: enabled and start collectd
  service:
    name: collectd
    state: started
    enabled: yes
