---
- hosts: ec2
  become: true
  
  tasks:
  - name: install apache and make sure it is running
    yum: 
      name: httpd
      state: present
  - name: start and enable apache 
    service: 
      name: httpd 
      state: started 
      enabled: yes 
  - name: install java
    yum: 
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tcl-devel for python
    yum:
      name: tcl-devel
      state: present
  - name: install openssl-devel for python
    yum:
      name: openssl-devel
      state: present
  - name: install rpm key for elasticserach
    rpm_key:
      key: https://packages.elastic.co/GPG-KEY-elasticsearch
      state: present
  - name: yum elastic repo
    yum_repository:
      name: elasticsearch-2.x
      description: Elasticsearch repository for 2.x packages
      baseurl: https://packages.elastic.co/elasticsearch/2.x/centos
      gpgcheck: 1
      gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
      enabled: 1
      state: present
  - name: install elasticsearch
    yum: 
      name: elasticsearch 
      state: present
  - name: start and run elasticsearch
    service: 
      name: elasticsearch
      state: started
      enabled: yes
  - name: add users
    user: 
      name: jchase 
      comment: "James Chase"
      groups: wheel
  - name: install ssh key
    authorized_key: 
      user: jchase
      key: "{{ lookup( 'file', '~/Downloads/jchase-us-east.public') }}"
  - name: install more ssh keys
    authorized_key:
      user: jchase
      key: "{{ lookup( './templates/public_keys/jchase-us-east.pub') }}"
  - name: install ssh key for calling user (for fun) 
    authorized_key: 
      user: jchase
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  - name: add wheel to passwordless sudo
    blockinfile:
      dest: /etc/sudoers
      block: |
        %wheel    ALL=(ALL)   NOPASSWD: ALL        
...
