---
- name: push the grafana repo
  template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo 

- name: install grafana
  yum:
    name: grafana
    state: present
   
- name: start and enable grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
