---
- name: add users
  user:
    name: jchase
    comment: "James Chase"
    groups: wheel
- name: install ssh key
  authorized_key:
    user: jchase
    key: "{{ lookup( 'file', '~/Downloads/jchase-us-east.public') }}"
- name: install jchase macbook ssh key
  authorized_key:
    user: jchase
    key: jchase-macbook.pub
- name: add wheel to passwordless sudo
  blockinfile:
    dest: /etc/sudoers
    block: |
      %wheel    ALL=(ALL)   NOPASSWD: ALL
...
